services:
    tjb_formextension.form.type.treepicker:
        class: TJB\FormExtensionsBundle\Form\Type\TreePickerType
        arguments: [ @Doctrine ]
        tags:
            - { name: form.type, alias: tjb_treepicker_type }